/// Flutter icons CherryToastIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CherryToastIcons
///      fonts:
///       - asset: fonts/CherryToastIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CherryToastIcons {
  CherryToastIcons._();

  static const _kFontFam = 'CherryToastIcons';
  static const String? _kFontPkg = null;

  static const IconData warning = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checked = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_button = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
